name: Playwright Hello World

on:
  workflow_dispatch:    # allows manual runs
  schedule:
    - cron: '0 0 * * *' # optional: daily at 00:00 UTC (change as you like)

jobs:
  run-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Cache pip packages
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Playwright Python package
        run: pip install -r requirements.txt

      # Cache Playwright browsers
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright browsers (and required OS deps)
        run: python -m playwright install chromium --with-deps
      
      - name: Create Gmail credentials.json
        run: echo "${{ secrets.GMAIL_CREDENTIALS }}" > credentials.json
      - name: Write secrets
        run: echo '${{ secrets.GOOGLE_TOKEN }}' > token.json

      - name: Run hello_playwright.py
        env:
          db_connection_url: ${{ secrets.db_connection_url }}   # <--- inject secret as env var
          nysa_user_id: ${{ secrets.nysa_user_id }}             # <--- inject secret as env var
          nysa_password: ${{ secrets.nysa_password }}         # <--- inject secret as env var
          hirise_user_id: ${{ secrets.hirise_user_id }}
          hirise_password: ${{ secrets.hirise_password }}
        run: python hello_playwright.py
